_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 128
data_frac:
    value: 0.05
emb_dim:
    value: 64
epochs:
    value: 5
hidden_dim:
    value: 1024
latent_dim:
    value: 256
learning_rate:
    value: 0.001
